# Change these first
owner: Dossierr  # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees:
  - two-trick-pony-NL


sites:
  - name: Webserver
    url: https://dossierr.vdotvo9a4e2a6.eu-central-1.cs.amazonlightsail.com
  - name: GPT Engine 
    url: https://dossierr.vdotvo9a4e2a6.eu-central-1.cs.amazonlightsail.com/q/
  - name: NGINX Reverse Proxy
    url: https://dossierr.vdotvo9a4e2a6.eu-central-1.cs.amazonlightsail.com/healthcheck

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.mapmaker.nl
  logoUrl: https://raw.githubusercontent.com/Dossierr/noncode/main/logowide.png
  name: Dossierr Status page
  introTitle: "**Status page**"
  introMessage: "This is the status page for Dossierr. Check the associated issues in case of downtime."
  theme: light
  css: "nav {background-color: #fae050;}"
  navbar:
    - title: Status
      href: /
    - title: Incident Issues
      href: https://github.com/dossierr/Status-Page/issues?q=is%3Aissue+is%3Aopen

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
